name: macos-build

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build_and_test:
    name: Build vfs on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: macos-latest
        include:
          - os: macos-latest
            compiler: g++-latest
            target: Macos


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure
        run: mkdir build && cmake -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Compile a release build of vfs
        run: make -C build/ -j4
